# Generated by Django 4.2.7 on 2023-12-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheeldiameter',
            name='diameter',
            field=models.CharField(help_text='Укажите диаметр колеса', max_length=5, verbose_name='Диаметр колеса'),
        ),
    ]
